version: '3.8'

services:
  relayer-staging:
    build:
      context: ../../
      dockerfile: packages/relayer/Dockerfile.staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
    image: relayer-staging
    volumes:
      - /tmp/pp_relayer.sqlite:/pp_relayer.sqlite
      - ./config.example.json:/build/config.json
      - ../circuits/artifacts:/build/node_modules/@0xbow/privacy-pools-core-sdk/dist/node/artifacts
    # might have to rebuild the circuit artifacts on sdk
